# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/nickorlow/vivado/hello_world_dma/hello_world_dma.srcs/sources_1/bd/top/ip/top_util_ds_buf_0/top_util_ds_buf_0.xci
# IP: The module: 'top_util_ds_buf_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/nickorlow/vivado/hello_world_dma/hello_world_dma.gen/sources_1/bd/top/ip/top_util_ds_buf_0/top_util_ds_buf_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_util_ds_buf_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/nickorlow/vivado/hello_world_dma/hello_world_dma.gen/sources_1/bd/top/ip/top_util_ds_buf_0/top_util_ds_buf_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_util_ds_buf_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/nickorlow/vivado/hello_world_dma/hello_world_dma.srcs/sources_1/bd/top/ip/top_util_ds_buf_0/top_util_ds_buf_0.xci
# IP: The module: 'top_util_ds_buf_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/nickorlow/vivado/hello_world_dma/hello_world_dma.gen/sources_1/bd/top/ip/top_util_ds_buf_0/top_util_ds_buf_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_util_ds_buf_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/nickorlow/vivado/hello_world_dma/hello_world_dma.gen/sources_1/bd/top/ip/top_util_ds_buf_0/top_util_ds_buf_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_util_ds_buf_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
